[package]
name = "dexompiler"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
axmldecoder = { git = "https://github.com/yourlogarithm/axmldecoder.git", version = "0.6.0" }
clap = { version = "4.4.10", features = ["derive"] }
dex = "0.5.0"
indicatif = { version = "0.17.7", features = ["rayon"] }
num-derive = "0.4.1"
num-traits = "0.2.17"
num_cpus = "1.16.0"
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["rc"] }
serde_json = "1.0.108"
zip = "0.6.6"
